version: "3"

services:
  vlsp_mongo:
    image: mongo:latest
    container_name: vlsp_mongo
    volumes:
      - vlsp_mongo:/data/db
    environment:
      - TZ=Asia/Ho_Chi_Minh
    
  vlsp_server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    container_name: vlsp_server
    restart: always
    ports: 
      - "5999:5000"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PORT=5000
      - MONGODB_URL=mongodb://vlsp_mongo:27017/vlsp
  
  vlsp_client:
    build:
      context: ../client
      dockerfile: ../docker/client.Dockerfile
    container_name: vlsp_client
    restart: always
    ports: 
      - "3999:3000"
    environment: 
      - TZ=Asia/Ho_Chi_Minh

volumes: 
  vlsp_mongo: